# Generated by Django 5.1.6 on 2025-02-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('detalhes', models.CharField(max_length=40)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='itens_images/')),
            ],
        ),
    ]
