# Generated by Django 5.1.6 on 2025-02-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imagem',
        ),
    ]
