# Generated by Django 5.1.6 on 2025-02-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_remove_item_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='detalhes',
            field=models.CharField(choices=[('em_andamento', 'Em andamento'), ('dropado', 'Dropado')], default='em_andamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
