# Generated by Django 5.1.6 on 2025-02-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_item_cap_alter_item_detalhes_alter_item_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nota',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='detalhes',
            field=models.CharField(choices=[('em_andamento', 'Em andamento'), ('dropado', 'Dropado'), ('finalizado', 'Finalizado')], default='em_andamento', max_length=20),
        ),
    ]
